# Generated by Django 5.1.2 on 2024-10-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan_customer',
            fields=[
                ('lc', models.CharField(max_length=20, primary_key='lc', serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('numberofyears', models.FloatField()),
                ('typeofinterest', models.CharField(max_length=20)),
                ('typeofloan', models.CharField(max_length=20)),
            ],
        ),
    ]
